version: '3'

services:
  db:
    container_name: ${service_name}-db
    image: mysql:5.7
    networks:
      - wifi-locate
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${db_name}

  locate:
    container_name: ${service_name}-locate
    build:
      context: .
      target: locate
    networks:
      - wifi-locate
    depends_on:
      - db

  gateway:
    container_name: ${service_name}-gateway
    build:
      context: .
      target: gateway
    networks:
      - wifi-locate
    ports: 
      - 8080:8080

networks:
  wifi-locate:
